apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlcg-converter
  labels:
    app: wlcg-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlcg-converter
  template:
    metadata:
      labels:
        app: wlcg-converter
    spec:
      containers:
      - name: wlcg-converter
        image: registry.cern.ch/wlcg-ops/wlcg-converter
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /etc/wlcg_converter
        - name: certs
          mountPath: /etc/wlcg_converter/certs
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: wlcg-converter-config
      - name: certs
        secret:
          secretName: wlcg-converter-certs
          optional: true